// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: GIS/v1/bus.proto

package gis

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestBus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Stop        []string `protobuf:"bytes,2,rep,name=stop,proto3" json:"stop,omitempty"`
	IsRoundtrip bool     `protobuf:"varint,3,opt,name=is_roundtrip,json=isRoundtrip,proto3" json:"is_roundtrip,omitempty"`
}

func (x *RequestBus) Reset() {
	*x = RequestBus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GIS_v1_bus_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestBus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestBus) ProtoMessage() {}

func (x *RequestBus) ProtoReflect() protoreflect.Message {
	mi := &file_GIS_v1_bus_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestBus.ProtoReflect.Descriptor instead.
func (*RequestBus) Descriptor() ([]byte, []int) {
	return file_GIS_v1_bus_proto_rawDescGZIP(), []int{0}
}

func (x *RequestBus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RequestBus) GetStop() []string {
	if x != nil {
		return x.Stop
	}
	return nil
}

func (x *RequestBus) GetIsRoundtrip() bool {
	if x != nil {
		return x.IsRoundtrip
	}
	return false
}

var File_GIS_v1_bus_proto protoreflect.FileDescriptor

var file_GIS_v1_bus_proto_rawDesc = []byte{
	0x0a, 0x10, 0x47, 0x49, 0x53, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x67, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x22, 0x57, 0x0a, 0x0a, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x74, 0x6f, 0x70, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x73, 0x74, 0x6f, 0x70,
	0x12, 0x21, 0x0a, 0x0c, 0x69, 0x73, 0x5f, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x74, 0x72, 0x69, 0x70,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x74,
	0x72, 0x69, 0x70, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x73, 0x79, 0x61, 0x6c, 0x73, 0x72, 0x2f, 0x47, 0x49, 0x53, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x47, 0x49, 0x53, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x3b, 0x67, 0x69, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_GIS_v1_bus_proto_rawDescOnce sync.Once
	file_GIS_v1_bus_proto_rawDescData = file_GIS_v1_bus_proto_rawDesc
)

func file_GIS_v1_bus_proto_rawDescGZIP() []byte {
	file_GIS_v1_bus_proto_rawDescOnce.Do(func() {
		file_GIS_v1_bus_proto_rawDescData = protoimpl.X.CompressGZIP(file_GIS_v1_bus_proto_rawDescData)
	})
	return file_GIS_v1_bus_proto_rawDescData
}

var file_GIS_v1_bus_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_GIS_v1_bus_proto_goTypes = []interface{}{
	(*RequestBus)(nil), // 0: gis.v1.RequestBus
}
var file_GIS_v1_bus_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_GIS_v1_bus_proto_init() }
func file_GIS_v1_bus_proto_init() {
	if File_GIS_v1_bus_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_GIS_v1_bus_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestBus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_GIS_v1_bus_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GIS_v1_bus_proto_goTypes,
		DependencyIndexes: file_GIS_v1_bus_proto_depIdxs,
		MessageInfos:      file_GIS_v1_bus_proto_msgTypes,
	}.Build()
	File_GIS_v1_bus_proto = out.File
	file_GIS_v1_bus_proto_rawDesc = nil
	file_GIS_v1_bus_proto_goTypes = nil
	file_GIS_v1_bus_proto_depIdxs = nil
}
