// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: GIS/v1/gis.proto

package gis

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestStop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Longitude    int32           `protobuf:"varint,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude     int32           `protobuf:"varint,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	RoadDistance []*RoadDistance `protobuf:"bytes,4,rep,name=roadDistance,proto3" json:"roadDistance,omitempty"`
}

func (x *RequestStop) Reset() {
	*x = RequestStop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GIS_v1_gis_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestStop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestStop) ProtoMessage() {}

func (x *RequestStop) ProtoReflect() protoreflect.Message {
	mi := &file_GIS_v1_gis_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestStop.ProtoReflect.Descriptor instead.
func (*RequestStop) Descriptor() ([]byte, []int) {
	return file_GIS_v1_gis_proto_rawDescGZIP(), []int{0}
}

func (x *RequestStop) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RequestStop) GetLongitude() int32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *RequestStop) GetLatitude() int32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *RequestStop) GetRoadDistance() []*RoadDistance {
	if x != nil {
		return x.RoadDistance
	}
	return nil
}

type RoadDistance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Curvature int32  `protobuf:"varint,2,opt,name=curvature,proto3" json:"curvature,omitempty"`
	Velocity  int32  `protobuf:"varint,3,opt,name=velocity,proto3" json:"velocity,omitempty"`
}

func (x *RoadDistance) Reset() {
	*x = RoadDistance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GIS_v1_gis_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoadDistance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoadDistance) ProtoMessage() {}

func (x *RoadDistance) ProtoReflect() protoreflect.Message {
	mi := &file_GIS_v1_gis_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoadDistance.ProtoReflect.Descriptor instead.
func (*RoadDistance) Descriptor() ([]byte, []int) {
	return file_GIS_v1_gis_proto_rawDescGZIP(), []int{1}
}

func (x *RoadDistance) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoadDistance) GetCurvature() int32 {
	if x != nil {
		return x.Curvature
	}
	return 0
}

func (x *RoadDistance) GetVelocity() int32 {
	if x != nil {
		return x.Velocity
	}
	return 0
}

type ResponseWithOnlyError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Erorr string `protobuf:"bytes,1,opt,name=erorr,proto3" json:"erorr,omitempty"`
}

func (x *ResponseWithOnlyError) Reset() {
	*x = ResponseWithOnlyError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GIS_v1_gis_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseWithOnlyError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseWithOnlyError) ProtoMessage() {}

func (x *ResponseWithOnlyError) ProtoReflect() protoreflect.Message {
	mi := &file_GIS_v1_gis_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseWithOnlyError.ProtoReflect.Descriptor instead.
func (*ResponseWithOnlyError) Descriptor() ([]byte, []int) {
	return file_GIS_v1_gis_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseWithOnlyError) GetErorr() string {
	if x != nil {
		return x.Erorr
	}
	return ""
}

type RequestBus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Stop        []string `protobuf:"bytes,2,rep,name=stop,proto3" json:"stop,omitempty"`
	IsRoundtrip bool     `protobuf:"varint,3,opt,name=is_roundtrip,json=isRoundtrip,proto3" json:"is_roundtrip,omitempty"`
}

func (x *RequestBus) Reset() {
	*x = RequestBus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GIS_v1_gis_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestBus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestBus) ProtoMessage() {}

func (x *RequestBus) ProtoReflect() protoreflect.Message {
	mi := &file_GIS_v1_gis_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestBus.ProtoReflect.Descriptor instead.
func (*RequestBus) Descriptor() ([]byte, []int) {
	return file_GIS_v1_gis_proto_rawDescGZIP(), []int{3}
}

func (x *RequestBus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RequestBus) GetStop() []string {
	if x != nil {
		return x.Stop
	}
	return nil
}

func (x *RequestBus) GetIsRoundtrip() bool {
	if x != nil {
		return x.IsRoundtrip
	}
	return false
}

type RequestRoute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To   string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
}

func (x *RequestRoute) Reset() {
	*x = RequestRoute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GIS_v1_gis_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRoute) ProtoMessage() {}

func (x *RequestRoute) ProtoReflect() protoreflect.Message {
	mi := &file_GIS_v1_gis_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRoute.ProtoReflect.Descriptor instead.
func (*RequestRoute) Descriptor() ([]byte, []int) {
	return file_GIS_v1_gis_proto_rawDescGZIP(), []int{4}
}

func (x *RequestRoute) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *RequestRoute) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type ResponseRoute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error     string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	TotalTime float64  `protobuf:"fixed64,2,opt,name=total_time,json=totalTime,proto3" json:"total_time,omitempty"`
	Stops     []string `protobuf:"bytes,3,rep,name=stops,proto3" json:"stops,omitempty"`
}

func (x *ResponseRoute) Reset() {
	*x = ResponseRoute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GIS_v1_gis_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseRoute) ProtoMessage() {}

func (x *ResponseRoute) ProtoReflect() protoreflect.Message {
	mi := &file_GIS_v1_gis_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseRoute.ProtoReflect.Descriptor instead.
func (*ResponseRoute) Descriptor() ([]byte, []int) {
	return file_GIS_v1_gis_proto_rawDescGZIP(), []int{5}
}

func (x *ResponseRoute) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ResponseRoute) GetTotalTime() float64 {
	if x != nil {
		return x.TotalTime
	}
	return 0
}

func (x *ResponseRoute) GetStops() []string {
	if x != nil {
		return x.Stops
	}
	return nil
}

var File_GIS_v1_gis_proto protoreflect.FileDescriptor

var file_GIS_v1_gis_proto_rawDesc = []byte{
	0x0a, 0x10, 0x47, 0x49, 0x53, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x69, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x67, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x72, 0x70, 0x63, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x95, 0x01, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x74, 0x6f, 0x70,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75,
	0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x38,
	0x0a, 0x0c, 0x72, 0x6f, 0x61, 0x64, 0x44, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f,
	0x61, 0x64, 0x44, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x0c, 0x72, 0x6f, 0x61, 0x64,
	0x44, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x5c, 0x0a, 0x0c, 0x52, 0x6f, 0x61, 0x64,
	0x44, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x63, 0x75, 0x72, 0x76, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x63, 0x75, 0x72, 0x76, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x65,
	0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x76, 0x65,
	0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x22, 0x2d, 0x0a, 0x15, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x57, 0x69, 0x74, 0x68, 0x4f, 0x6e, 0x6c, 0x79, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x72, 0x6f, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x72, 0x6f, 0x72, 0x72, 0x22, 0x57, 0x0a, 0x0a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x42, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x74, 0x6f, 0x70, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x73, 0x74, 0x6f, 0x70, 0x12, 0x21, 0x0a, 0x0c, 0x69,
	0x73, 0x5f, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x74, 0x72, 0x69, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0b, 0x69, 0x73, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x74, 0x72, 0x69, 0x70, 0x22, 0x32,
	0x0a, 0x0c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72,
	0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x74, 0x6f, 0x22, 0x5a, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x6f,
	0x75, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x70,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x70, 0x73, 0x32, 0xea,
	0x01, 0x0a, 0x03, 0x47, 0x49, 0x53, 0x12, 0x4b, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x53, 0x74, 0x6f, 0x70, 0x12, 0x13, 0x2e, 0x67, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x74, 0x6f, 0x70, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x22, 0x10, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0a, 0x22, 0x05, 0x2f, 0x73, 0x74, 0x6f, 0x70,
	0x3a, 0x01, 0x2a, 0x12, 0x48, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x75, 0x73,
	0x12, 0x12, 0x2e, 0x67, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x42, 0x75, 0x73, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x0f, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x09, 0x22, 0x04, 0x2f, 0x62, 0x75, 0x73, 0x3a, 0x01, 0x2a, 0x12, 0x4c, 0x0a,
	0x0a, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x14, 0x2e, 0x67, 0x69,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x6f, 0x75, 0x74,
	0x65, 0x1a, 0x15, 0x2e, 0x67, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x22, 0x11, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0b,
	0x22, 0x06, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x3a, 0x01, 0x2a, 0x42, 0x2a, 0x5a, 0x28, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x79, 0x61, 0x6c, 0x73, 0x72,
	0x2f, 0x47, 0x49, 0x53, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x47, 0x49, 0x53, 0x2d, 0x61, 0x70, 0x69,
	0x2f, 0x76, 0x31, 0x3b, 0x67, 0x69, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_GIS_v1_gis_proto_rawDescOnce sync.Once
	file_GIS_v1_gis_proto_rawDescData = file_GIS_v1_gis_proto_rawDesc
)

func file_GIS_v1_gis_proto_rawDescGZIP() []byte {
	file_GIS_v1_gis_proto_rawDescOnce.Do(func() {
		file_GIS_v1_gis_proto_rawDescData = protoimpl.X.CompressGZIP(file_GIS_v1_gis_proto_rawDescData)
	})
	return file_GIS_v1_gis_proto_rawDescData
}

var file_GIS_v1_gis_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_GIS_v1_gis_proto_goTypes = []interface{}{
	(*RequestStop)(nil),           // 0: gis.v1.RequestStop
	(*RoadDistance)(nil),          // 1: gis.v1.RoadDistance
	(*ResponseWithOnlyError)(nil), // 2: gis.v1.ResponseWithOnlyError
	(*RequestBus)(nil),            // 3: gis.v1.RequestBus
	(*RequestRoute)(nil),          // 4: gis.v1.RequestRoute
	(*ResponseRoute)(nil),         // 5: gis.v1.ResponseRoute
	(*emptypb.Empty)(nil),         // 6: google.protobuf.Empty
}
var file_GIS_v1_gis_proto_depIdxs = []int32{
	1, // 0: gis.v1.RequestStop.roadDistance:type_name -> gis.v1.RoadDistance
	0, // 1: gis.v1.GIS.CreateStop:input_type -> gis.v1.RequestStop
	3, // 2: gis.v1.GIS.CreateBus:input_type -> gis.v1.RequestBus
	4, // 3: gis.v1.GIS.BuildRoute:input_type -> gis.v1.RequestRoute
	6, // 4: gis.v1.GIS.CreateStop:output_type -> google.protobuf.Empty
	6, // 5: gis.v1.GIS.CreateBus:output_type -> google.protobuf.Empty
	5, // 6: gis.v1.GIS.BuildRoute:output_type -> gis.v1.ResponseRoute
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_GIS_v1_gis_proto_init() }
func file_GIS_v1_gis_proto_init() {
	if File_GIS_v1_gis_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_GIS_v1_gis_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestStop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GIS_v1_gis_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoadDistance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GIS_v1_gis_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseWithOnlyError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GIS_v1_gis_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestBus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GIS_v1_gis_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestRoute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GIS_v1_gis_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseRoute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_GIS_v1_gis_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_GIS_v1_gis_proto_goTypes,
		DependencyIndexes: file_GIS_v1_gis_proto_depIdxs,
		MessageInfos:      file_GIS_v1_gis_proto_msgTypes,
	}.Build()
	File_GIS_v1_gis_proto = out.File
	file_GIS_v1_gis_proto_rawDesc = nil
	file_GIS_v1_gis_proto_goTypes = nil
	file_GIS_v1_gis_proto_depIdxs = nil
}
