// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: GIS/v1/route.proto

package gis

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestRoute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To   string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
}

func (x *RequestRoute) Reset() {
	*x = RequestRoute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GIS_v1_route_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRoute) ProtoMessage() {}

func (x *RequestRoute) ProtoReflect() protoreflect.Message {
	mi := &file_GIS_v1_route_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRoute.ProtoReflect.Descriptor instead.
func (*RequestRoute) Descriptor() ([]byte, []int) {
	return file_GIS_v1_route_proto_rawDescGZIP(), []int{0}
}

func (x *RequestRoute) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *RequestRoute) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type ResponseRoute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error     string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	TotalTime float64  `protobuf:"fixed64,2,opt,name=total_time,json=totalTime,proto3" json:"total_time,omitempty"`
	Stops     []string `protobuf:"bytes,3,rep,name=stops,proto3" json:"stops,omitempty"`
}

func (x *ResponseRoute) Reset() {
	*x = ResponseRoute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GIS_v1_route_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseRoute) ProtoMessage() {}

func (x *ResponseRoute) ProtoReflect() protoreflect.Message {
	mi := &file_GIS_v1_route_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseRoute.ProtoReflect.Descriptor instead.
func (*ResponseRoute) Descriptor() ([]byte, []int) {
	return file_GIS_v1_route_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseRoute) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ResponseRoute) GetTotalTime() float64 {
	if x != nil {
		return x.TotalTime
	}
	return 0
}

func (x *ResponseRoute) GetStops() []string {
	if x != nil {
		return x.Stops
	}
	return nil
}

var File_GIS_v1_route_proto protoreflect.FileDescriptor

var file_GIS_v1_route_proto_rawDesc = []byte{
	0x0a, 0x12, 0x47, 0x49, 0x53, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x67, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x22, 0x32, 0x0a, 0x0c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d,
	0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f,
	0x22, 0x5a, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x6f, 0x75, 0x74,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x70, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x70, 0x73, 0x42, 0x2a, 0x5a, 0x28,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x79, 0x61, 0x6c, 0x73,
	0x72, 0x2f, 0x47, 0x49, 0x53, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x47, 0x49, 0x53, 0x2d, 0x61, 0x70,
	0x69, 0x2f, 0x76, 0x31, 0x3b, 0x67, 0x69, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_GIS_v1_route_proto_rawDescOnce sync.Once
	file_GIS_v1_route_proto_rawDescData = file_GIS_v1_route_proto_rawDesc
)

func file_GIS_v1_route_proto_rawDescGZIP() []byte {
	file_GIS_v1_route_proto_rawDescOnce.Do(func() {
		file_GIS_v1_route_proto_rawDescData = protoimpl.X.CompressGZIP(file_GIS_v1_route_proto_rawDescData)
	})
	return file_GIS_v1_route_proto_rawDescData
}

var file_GIS_v1_route_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_GIS_v1_route_proto_goTypes = []interface{}{
	(*RequestRoute)(nil),  // 0: gis.v1.RequestRoute
	(*ResponseRoute)(nil), // 1: gis.v1.ResponseRoute
}
var file_GIS_v1_route_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_GIS_v1_route_proto_init() }
func file_GIS_v1_route_proto_init() {
	if File_GIS_v1_route_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_GIS_v1_route_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestRoute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GIS_v1_route_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseRoute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_GIS_v1_route_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GIS_v1_route_proto_goTypes,
		DependencyIndexes: file_GIS_v1_route_proto_depIdxs,
		MessageInfos:      file_GIS_v1_route_proto_msgTypes,
	}.Build()
	File_GIS_v1_route_proto = out.File
	file_GIS_v1_route_proto_rawDesc = nil
	file_GIS_v1_route_proto_goTypes = nil
	file_GIS_v1_route_proto_depIdxs = nil
}
