// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: GIS/v1/stop.proto

package gis

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestStop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Longitude    int32           `protobuf:"varint,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude     int32           `protobuf:"varint,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	RoadDistance []*RoadDistance `protobuf:"bytes,4,rep,name=roadDistance,proto3" json:"roadDistance,omitempty"`
}

func (x *RequestStop) Reset() {
	*x = RequestStop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GIS_v1_stop_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestStop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestStop) ProtoMessage() {}

func (x *RequestStop) ProtoReflect() protoreflect.Message {
	mi := &file_GIS_v1_stop_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestStop.ProtoReflect.Descriptor instead.
func (*RequestStop) Descriptor() ([]byte, []int) {
	return file_GIS_v1_stop_proto_rawDescGZIP(), []int{0}
}

func (x *RequestStop) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RequestStop) GetLongitude() int32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *RequestStop) GetLatitude() int32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *RequestStop) GetRoadDistance() []*RoadDistance {
	if x != nil {
		return x.RoadDistance
	}
	return nil
}

type RoadDistance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Curvature int32  `protobuf:"varint,2,opt,name=curvature,proto3" json:"curvature,omitempty"`
	Velocity  int32  `protobuf:"varint,3,opt,name=velocity,proto3" json:"velocity,omitempty"`
}

func (x *RoadDistance) Reset() {
	*x = RoadDistance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GIS_v1_stop_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoadDistance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoadDistance) ProtoMessage() {}

func (x *RoadDistance) ProtoReflect() protoreflect.Message {
	mi := &file_GIS_v1_stop_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoadDistance.ProtoReflect.Descriptor instead.
func (*RoadDistance) Descriptor() ([]byte, []int) {
	return file_GIS_v1_stop_proto_rawDescGZIP(), []int{1}
}

func (x *RoadDistance) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoadDistance) GetCurvature() int32 {
	if x != nil {
		return x.Curvature
	}
	return 0
}

func (x *RoadDistance) GetVelocity() int32 {
	if x != nil {
		return x.Velocity
	}
	return 0
}

var File_GIS_v1_stop_proto protoreflect.FileDescriptor

var file_GIS_v1_stop_proto_rawDesc = []byte{
	0x0a, 0x11, 0x47, 0x49, 0x53, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x74, 0x6f, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x67, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x22, 0x95, 0x01, 0x0a, 0x0b,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x74, 0x6f, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x38, 0x0a, 0x0c, 0x72, 0x6f, 0x61,
	0x64, 0x44, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x67, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x61, 0x64, 0x44, 0x69, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x0c, 0x72, 0x6f, 0x61, 0x64, 0x44, 0x69, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x22, 0x5c, 0x0a, 0x0c, 0x52, 0x6f, 0x61, 0x64, 0x44, 0x69, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x75, 0x72, 0x76, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x75, 0x72, 0x76,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x76, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74,
	0x79, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x73, 0x79, 0x61, 0x6c, 0x73, 0x72, 0x2f, 0x47, 0x49, 0x53, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x47,
	0x49, 0x53, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x3b, 0x67, 0x69, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_GIS_v1_stop_proto_rawDescOnce sync.Once
	file_GIS_v1_stop_proto_rawDescData = file_GIS_v1_stop_proto_rawDesc
)

func file_GIS_v1_stop_proto_rawDescGZIP() []byte {
	file_GIS_v1_stop_proto_rawDescOnce.Do(func() {
		file_GIS_v1_stop_proto_rawDescData = protoimpl.X.CompressGZIP(file_GIS_v1_stop_proto_rawDescData)
	})
	return file_GIS_v1_stop_proto_rawDescData
}

var file_GIS_v1_stop_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_GIS_v1_stop_proto_goTypes = []interface{}{
	(*RequestStop)(nil),  // 0: gis.v1.RequestStop
	(*RoadDistance)(nil), // 1: gis.v1.RoadDistance
}
var file_GIS_v1_stop_proto_depIdxs = []int32{
	1, // 0: gis.v1.RequestStop.roadDistance:type_name -> gis.v1.RoadDistance
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_GIS_v1_stop_proto_init() }
func file_GIS_v1_stop_proto_init() {
	if File_GIS_v1_stop_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_GIS_v1_stop_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestStop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GIS_v1_stop_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoadDistance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_GIS_v1_stop_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GIS_v1_stop_proto_goTypes,
		DependencyIndexes: file_GIS_v1_stop_proto_depIdxs,
		MessageInfos:      file_GIS_v1_stop_proto_msgTypes,
	}.Build()
	File_GIS_v1_stop_proto = out.File
	file_GIS_v1_stop_proto_rawDesc = nil
	file_GIS_v1_stop_proto_goTypes = nil
	file_GIS_v1_stop_proto_depIdxs = nil
}
