version: '3.7'

services:
  gis:
    build: .
    container_name: gis
    hostname: gis
    restart: always

    depends_on:
      - redis
      - postgres

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    env_file:
      - .env

  redis:
    image: redis:7
    restart: always
    hostname: redis
    ports:
     - 6379:6379
    volumes:
      - redis-data:/data

  postgres:
    image: 'postgres:latest'
    container_name: postgres

    environment:
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/data

volumes:
  redis-data:
  postgres-data: