version: '3.7'

services:
  redis:
    image: redis:7
    restart: always
    hostname: redis
    ports:
     - 6379:6379
    volumes:
      - redis-data:/data

  postgres:
    image: 'postgres:latest'
    hostname: postgres

    environment:
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/data

volumes:
  redis-data:
  postgres-data: