### POST request with json body
POST http://localhost:9098/stop/v1
Content-Type: application/json

{
    "name": "Lublino-1",
    "longitude": 10,
    "latitude": 10,
    "roadDistance": [
        {
            "name": "Lublino-2",
            "curvature": 30,
            "velocity": 15
        },
        {
            "name": "Lublino-3",
            "curvature": 20,
            "velocity": 15
        }
    ]
}

### POST request with json body
POST http://localhost:9098/stop/v1
Content-Type: application/json

{
    "name": "Lublino-2",
    "longitude": 30,
    "latitude": 10,
    "roadDistance": [
        {
            "name": "Lublino-1",
            "curvature": 30,
            "velocity": 15
        },
        {
            "name": "Lublino-3",
            "curvature": 20,
            "velocity": 15
        },
        {
            "name": "Lublino-4",
            "curvature": 40,
            "velocity": 15
        }
    ]
}

### POST request with json body
POST http://localhost:9098/stop/v1
Content-Type: application/json

{
    "name": "Lublino-3",
    "longitude": 32,
    "latitude": 43,
    "roadDistance": [
        {
            "name": "Lublino-1",
            "curvature": 30,
            "velocity": 15
        },
        {
            "name": "Lublino-2",
            "curvature": 30,
            "velocity": 15
        },
        {
            "name": "Lublino-4",
            "curvature": 15,
            "velocity": 15
        }
    ]
}

### POST request with json body
POST http://localhost:9098/stop/v1
Content-Type: application/json

{
    "name": "Lublino-4",
    "longitude": 32,
    "latitude": 43,
    "roadDistance": [
        {
            "name": "Lublino-2",
            "curvature": 40,
            "velocity": 15
        },
        {
            "name": "Lublino-3",
            "curvature": 15,
            "velocity": 15
        }
    ]
}

### POST request with json body
POST http://localhost:9098/bus/v1
Content-Type: application/json

{
    "name": "1",
    "is_roundtrip": true,
    "stop": [
        "Lublino-1",
        "Lublino-2",
        "Lublino-3"
    ]
}

### POST request with json body
POST http://localhost:9098/bus/v1
Content-Type: application/json

{
    "name": "2",
    "is_roundtrip": true,
    "stop": [
        "Lublino-3",
        "Lublino-2",
        "Lublino-4"
    ]
}

### POST request with json body
POST http://localhost:9098/bus/v1
Content-Type: application/json

{
    "name": "3",
    "is_roundtrip": true,
    "stop": [
        "Lublino-4",
        "Lublino-2",
        "Lublino-1"
    ]
}

### POST request with json body
POST http://localhost:9098/route/v1
Content-Type: application/json

{
    "from": "Lublino-1",
    "to": "Lublino-4"
}